# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [16]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [17]:
weather_csv = "../weatherPy/weather_df.csv"

weather_df = pd.read_csv(weather_csv)

weather_df.head()

,Unnamed: 0,City,Country,Temperature,Humidity,Cloudiness,Windspeed,Latitude,Longitude,Date
0,0,vaini,TO,75.36,83,75,8.05,-21.2000,-175.2000,1666877521
1,1,khatanga,RU,8.56,96,100,6.38,71.9667,102.5000,1666877522
2,2,ushuaia,AR,46.06,42,0,9.22,-54.8000,-68.3000,1666877522
3,3,barabai,ID,74.97,98,100,2.48,-2.5833,115.3833,1666877523
4,4,bathsheba,BB,86.61,70,40,24.16,13.2167,-59.5167,1666877523

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [18]:
#Gmaps api key
gmaps.configure(api_key=g_key)

# Humidity Weight
weights = weather_df["Humidity"]

# Lat/Lng locations 
locations = weather_df[["Latitude", "Longitude"]]

# Create map
fig = gmaps.figure(display_toolbar=True)

#add heatmap layer
fig.add_layer(gmaps.heatmap_layer(locations, weights=weights))
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [19]:
# Narrow down the DataFrame to find your ideal weather condition.
Narrow_weather_df = weather_df

Narrow_weather_df = weather_df.loc[(weather_df["Temperature"] < 94) & (weather_df["Temperature"] > 80) & (weather_df["Windspeed"]<7) &(weather_df["Humidity"]>65) & (weather_df["Cloudiness"] >50)]
# Drop null values
Narrow_weather_df.dropna

Narrow_weather_df

,Unnamed: 0,City,Country,Temperature,Humidity,Cloudiness,Windspeed,Latitude,Longitude,Date
125,125,cayenne,GF,86.04,70,75,6.91,4.9333,-52.3333,1666877410
141,141,ndjole,GA,80.08,82,100,3.74,-0.1783,10.7649,1666877579
201,201,kathu,TH,83.70,99,100,6.35,7.9178,98.3332,1666877604
211,211,ligayan,PH,81.46,76,100,5.12,4.6533,119.4706,1666877609
237,237,malabo,GQ,82.54,77,100,1.28,3.7500,8.7833,1666877622
281,281,calabozo,VE,84.16,68,97,4.07,8.9242,-67.4293,1666877644
304,304,lorengau,PG,82.17,77,100,5.68,-2.0226,147.2712,1666877653
339,339,bachaquero,VE,80.67,78,98,0.98,9.9694,-71.1494,1666877650
348,348,puerto carreno,CO,80.58,89,100,4.61,6.1890,-67.4859,1666877670
419,419,kupang,ID,81.03,82,100,4.07,-10.1667,123.5833,1666877703
447,447,da nang,VN,80.58,78,75,4.61,16.0678,108.2208,1666877718
485,485,namatanai,PG,80.29,81,100,5.35,-3.6667,152.4333,1666877741

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [20]:
#store variable/inclusion of Hotel name column
hotel_df = Narrow_weather_df
hotel_df['Hotel Name'] = ''

params = {
    "radius": 5000,
    "keyword":"hotel",
    "key": g_key
          }
url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

for index, row in hotel_df.iterrows():
    lat = row['Latitude']
    lng = row['Longitude']
    params["location"] = f'{lat},{lng}'

    response = requests.get(url, params=params).json()
    
    # extract results
    results = response['results']
    cities=row["City"]
    try:
        print(f'closest city is {cities}')
        
    except:
        print(f"Missing information for {cities}")

C:\Users\shupe\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

closest city is cayenne
closest city is ndjole
closest city is kathu
closest city is ligayan
closest city is malabo
closest city is calabozo
closest city is lorengau
closest city is bachaquero
closest city is puerto carreno
closest city is kupang
closest city is da nang
closest city is namatanai

In [21]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Latitude", "Longitude"]]

In [24]:
# Plot marker
fig.add_layer(gmaps.marker_layer(locations, info_box_content=hotel_info))